name: Dependabot

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/dependabot-core@stable
        with:
          command: "ruby lib/dependabot/script/update-check/run.rb"
          args: "--all-projects --ignore=python --directory=/github/workspace"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
